### ISSUE TITLE
[core] Running a local Lilypad network on windows had some hiccups

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#106]
- `chown` commands had to be `sudo`d - figure out a way for hardhat files to be owned by the correct user
- `chain` path had to be set outside of current folder or docker build commands would fail if `chain` is running because data folder is locked and there is a `COPY . . ` statement in the docker files (easy, just copy the right files)

**Comment by arsen3d** [comment]
PR: https://github.com/Lilypad-Tech/lilypad/pull/208

**Comment by arsen3d** [comment]
https://github.com/Lilypad-Tech/lilypad/issues/106

**Comment by richardbremner** [comment]
checkout the branch: arsen/fix-windows-docker-permission

chain-clean
chain
chain-boot

if that works, we can approve this
