### ISSUE TITLE
[core] Keep Devnet around and add infra for Testnet

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#124]
I want the engineering team to have access to a "deployed infra" without this being the infra where we are running the IncentivizedTestnet. If something is developed it can be tested locally and we can also do some QA on Devnet instead of doing it on the IncentivizedTestnet, similarly if we need to debug we can do so in Devnet.

This way we prevent our own usage from being part of the IncentivizedTestnet usage and it will give us some "real world" pain points that users have - to use the Devnet devs have to connect resource providers and running jobs here will give a more "genuine experience" - we may even consider Devnet our staging environment.

**Comment by AquiGorka** [comment]
I believe this is done right?
We have CI for Devnet (aws) and Testnet (arbitrum sepolia) in place.
The follow up task is to phase out gcp but there is a different ticket to track that.

**Comment by bgins** [comment]
We have a few clean up details to take care of in Devnet that are part of our internal checklist: https://github.com/Lilypad-Tech/internal/issues/39#issuecomment-2136057422

**Comment by bgins** [comment]
Completed the last items on the checklist and we have infra for Testnet up!
