### ISSUE TITLE
[core] Untangle faucet

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#127]
In a rush to fix the faucet, I used the new CI flow to deploy the faucet to AWS with the accompanying cloudflare tunnel pointing to `faucet.lilypad.tech`.

When we figure out how we want to proceed, we should take this into consideration.

My current line of thinking single word subdomains should be used for `mainnet` (faucet, api, solver, etc) and other subdomains should be explicit on which infra they use (`devnet (dev purposed infra)`: devnet-api, devnet-faucet, devnet-solver, `incentivized testnet (testnet)`: testnet-api, testnet-faucet, testnet-solver, etc).

**Comment by bgins** [comment]
One alternative to consider would be nested subdomains for everything other than `mainnet`. For example `faucet.devnet.lilypad.tech`, `api.devnet.lilypad.tech` and `faucet.testnet.lilypad.tech`, `api.testnet.lilypad.tech`.

**Comment by bgins** [comment]
We had a discussion about this and decided on the following:

- We will use the proposed nested subdomains like `faucet.devnet.lilypad.tech`
- Once the incentive network is live on `*.testnet.lilypad.tech` we can transition the existing faucet from `faucet.lilypad.tech` to `faucet.devnet.lilypad.tech`
- We won't need to run a faucet for the incentive network or mainnet

We will document the nested subdomain naming convention elsewhere to capture the idea outside of this issue.

**Comment by AquiGorka** [comment]
**Update**

We now have decided we do want a faucet for the testnet so, the [`eth-faucet`](https://github.com/Lilypad-Tech/eth-faucet) is still relevant and we want to keep it around.
This [pull request](https://github.com/Lilypad-Tech/eth-faucet/pull/3) sets up the configurations for arbitrum testnet and it has already been deployed to `faucet-testnet.lilypad.tech` and the workflow is in place for CI+CD.

The untangling at this point means tear down of the [`gcp faucet`](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#InstanceDetails:instanceId=i-0630eed8e47dc0744) AWS instance and the [`faucet tunnel`](https://one.dash.cloudflare.com/e53cb3293017a8c18bbe8d33aae050ac/networks/tunnels).

**Reminder**

Before merging that PR make sure the GitHub secrets all point to the testnet deploy instances (should be the case as it is rn, unless another deploy is needed for the GCP faucet)

**Comment by AquiGorka** [comment]
@arsen3d I'm assigning you to this task with the intention that you own the faucet as part of the `web3` front.

Context:
There are 3 (soon to be 2) faucets: GCP, Testnet public and Testnet internal.

- GCP is going to be deprecated soon. This is deployed from the `main` branch.
- Testnet public is the faucet that only gives away LP tokens. This is deployed from the `arsen/build-token-only-option` branch ([PR](https://github.com/Lilypad-Tech/eth-faucet/pull/4)).
- Testnet internal is the faucet that gives away ETH and LP tokens. This is deployed from the `arsen/bug-arbitrum-compatibility-parameters` branch ([PR](https://github.com/Lilypad-Tech/eth-faucet/pull/3)).

The intention is to have control on deploying the 2 testnet faucets from github actions (manual), so we'll need some secrets in place to trigger either deployments and work in the branches to be able to do their own thing or we add the actions and we deploy directly from the branches (proper branch names would be better than the ones out there), either way, your call.

Let me know if you have questions.

**Comment by richardbremner** [comment]
so we have determined to merge in both branches together, and be able to use a cli param to run either faucet, and then update the (manually triggered) deployment to run both.

**Comment by kquirapas** [comment]
@alvin-reyes  Almost resolved, but still waiting for @arsen3d 's insights on this issue.

The latest:

It seems this issue has already been resolved with the current network's setup and no further action is needed. As per faucet related problems, they will be opened in separate issues as per discussion with @bgins .

**Comment by alvin-reyes** [comment]
@kquirapas Ok please close this once the new ticket is out.

**Comment by kquirapas** [comment]
Adding this here for context upon closing.

![Image](https://github.com/user-attachments/assets/0d01cef9-b801-4821-97ff-36a634e09b24)

**Comment by kquirapas** [comment]
Adding this here for context upon closing.

![Image](https://github.com/user-attachments/assets/0d01cef9-b801-4821-97ff-36a634e09b24)
