### ISSUE TITLE
Once lilypad has pulled a module's git repo, it never updates it

### ISSUE THREAD

**Issue by lukemarsden** [Lilypad-Tech/lilypad#13]
Lilypad clones and uses the contents of git repos when using modules.

The code for this is here:
https://github.com/bacalhau-project/lilypad/blob/main/pkg/module/shortcuts/shortcuts.go
https://github.com/bacalhau-project/lilypad/blob/main/pkg/module/utils.go

The repos get cloned both in the CLI/client (job creator) and the server (resource provider).

Currently if you're a module developer, if any lilypad process (client or server) clones a repo, then you push more changes to it, the client or server will look in the _existing cached checkout_ for the new refs (e.g. tags) and fail to find them, resulting in errors like #9 

One solution would be to always pull the git repo before trying to find a ref in it (repo.ResolveRevision), but the problem with that is that it makes github.com (or wherever people are hosting their modules) into a single point of failure for our nice decentralized system. It would be better to only pull updates into the git repo _if finding the ref fails_. This way, if nodes have already run modules (which will normally be the case) and even if github is down, they'll still be able to proceed from their local cached state.

So:
- [ ] In the error handler for ResolveRevision https://github.com/bacalhau-project/lilypad/blob/main/pkg/module/utils.go#L89-L93, if the error is "ref not found" then try doing a git pull and then try to resolve the revision again. Only error if it fails the second time

Ideally write a test to cover this case. A fix without a test is acceptable though!

**Comment by DeveloperAlly** [comment]
He's away at the moment - safe to say it hasn't been!

**Comment by Nasfame** [comment]
Merged #19 

@lukemarsden can u close this ticket

**Comment by Zorlin** [comment]
Solved by #19 as far as I'm aware, haven't been able to reproduce this since.

We can open a separate issue for test coverage later.
