### ISSUE TITLE
Escaped json values are awkward

### ISSUE THREAD

**Issue by lukemarsden** [Lilypad-Tech/lilypad#14]
We json encode the string inputs to modules (i.e. the `-i` in `lilypad run cowsay:v0.0.1 -i Message=moo`) here: https://github.com/bacalhau-project/lilypad/blob/main/pkg/module/utils.go#L191-L199

Users are not trusted by nodes. Nodes should be able to trust module authors. If user input can make arbitrary changes to the job spec, this breaks the trust relationship.

Hence we want to avoid users doing nefarious things like including newlines and quotes in the untrusted user input.

This means that values in the json template, like https://github.com/bacalhau-project/lilypad-module-cowsay/blob/main/lilypad_module.json.tmpl#L16

like `{{.Message}}`, don't need to be escaped by the user with double quotes, but instead get automatically quoted for them. (Because the json serialization of a string has double quotes around it).

However, this makes it very awkward to substitute a value into an existing string, which many module authors want to do. In fact, we want to do it ourselves e.g. here: https://github.com/bacalhau-project/lilypad-module-sdxl/blob/main/lilypad_module.json.tmpl#L24

It would be much nicer to write
```
                    "PROMPT={{if .Prompt}}{{.Prompt}}{{else}}question mark floating in space{{end}}",
```
instead of 
```
                    {{if .PromptEnv}}{{.PromptEnv}}{{else}}"PROMPT=question mark floating in space"{{end}},
```
And then the user would be able to specify the prompt like `lilypad run sdxl:v0.9-lilypad1 -i Prompt="hoo haw"` instead of `lilypad run sdxl:v0.9-lilypad1 -i PromptEnv="PROMPT=hoo haw"` which is sad and annoying. But of course that would be insecure, because the user could write unquoted newlines and double quotes into PromptEnv and mess up the template.

To solve this, we need a way to securely substitute strings into other strings while still ensuring no JSON escape.

In `text/template`, which we use to parse the template you can define custom functions: https://pkg.go.dev/text/template#Template.Funcs

So,
- [ ] define a custom function which allows, given an untrusted user input string and, say, a printf style template string, for the module author to write:
```
                    {{subst "PROMPT=%s" .Prompt}},
```
Or something like that, where `subst` would:
* JSON decode `.Prompt` (we still want it encoded by default, for security reasons)
* printf it into the first given argument
* JSON encode the resulting string for security

**Comment by lukemarsden** [comment]
related to #3

**Comment by lukemarsden** [comment]
discussed here: https://bacalhauproject.slack.com/archives/C055K39J9QW/p1697231555849839?thread_ts=1697105936.121819&cid=C055K39J9QW

**Comment by Nasfame** [comment]
@lukemarsden custom functions don't work for substitution here is why:

```
          "URL": "{{printf "https://gateway.lighthouse.storage/ipfs/\%s .inputCid}}",
```

this would generate invalid json: "https://gateway.lighthouse.storage/ipfs/"<userVal>""

My suggestion is that: if the user input is valid json: No problem, don't encode it. Otherwise encode it

**Comment by Nasfame** [comment]
@lukemarsden valid json strings from users can be tested.

**Comment by lukemarsden** [comment]
> @lukemarsden custom functions don't work for substitution here is why:

Yes, that's why the subst function I proposed JSON decodes the value before substituting it, then reencodes it

**Comment by Nasfame** [comment]
that could work. Although it needs to be doced

**Comment by Nasfame** [comment]
@lukemarsden can u review #17
