### ISSUE TITLE
[core] Verify releases build not using Wings account and make sure no new releases are available til we release testnet

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#149]

**Comment by bgins** [comment]
If we are planning to move away from CircleCI, we could delete the release workflow: https://github.com/Lilypad-Tech/lilypad/blob/main/.circleci/config.yml. We could cut releases manually until we have another plan in place.

Thoughts?

**Comment by AquiGorka** [comment]
Closing in favor of: https://github.com/Lilypad-Tech/lilypad/issues/168
