### ISSUE TITLE
[open source] Define strategy

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#173]
- How to run a local network to have a playground for external devs to implement things? (local development writeup for open source contributors)
- How will we process open source contributions? (who reviews, how, when, why?)
- Call out for all interested parties (from our networks)
- Incentives !!! Incentivized Open Source strategy, how, when, why?

**Comment by AquiGorka** [comment]
Closing in favor of: https://github.com/Lilypad-Tech/lilypad/issues/168

**Comment by developersteve** [comment]
Adding an additional note here for a monthly community open source spotlight to talk about the contribs made.

**Comment by bgins** [comment]
We have defined our open source strategy and will be announcing it soon! See referenced issues above for associated documents.
