### ISSUE TITLE
Arbitrum faucet funds not enough to run jobs

### ISSUE THREAD

**Issue by PBillingsby** [Lilypad-Tech/lilypad#186]
### Description
I added the new network information (Lilypad and Arbitrum) and requested funds from the Arbitrum Sepolia faucet. I received 0.0001 tokens and when I attempted to run a job I got the following error:

```
2024-06-25T10:15:09-04:00 ERR ../runner/work/lilypad/lilypad/pkg/jobcreator/controller.go:267 > 🟢 JC error calling agree tx for deal="insufficient funds for gas * price + value: address 0x502c9904C193629a105DC7EBD946C23c7ECf0695 have 100000000000000 want 1999223400000000"
```

### Steps to Reproduce
1. With a new private key, add Lilypad and Arbitrum network information
2. Import Lilypad token
3. Add funds via faucets (20 LP, 0.0001 Arb Sepolia)
4. Attempt to run a job from CLI

### Expected vs. Actual Behavior
- **Expected:** I expected to have enough funds to run a job
- **Actual:** I got an error of insufficient funds

**Comment by arsen3d** [comment]
Looks like 0.0001 is not enough for transaction.
This transactions requires 0.0019992234
https://eth-converter.com/
get more eth from here: https://faucets.chain.link/arbitrum-sepolia
they offer 0.1

**Comment by alvin-reyes** [comment]
We already replenished the faucets.
