### ISSUE TITLE
[core] Does the job creator need the solver PK? Or using it caused a fluke?

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#196]
The setup for local dev in doppler has the `job creator` use the `solver`'s PK.
During the war room for the situations that happened when we were announcing the incentivized Testnet phase, at one moment we could not run a single job - we noticed jobs hung at the `job creator` level/steps (which could have been a direct error on our end to try to run a job while the service was being deployed).

After a while, with all services deployed and in place, we tried swapping the `job creator`'s PK for the `solver`'s PK, from that moment on, all of our `cowsay` jobs worked (all, `100%`, we ran less that 10), so maybe this was needed?

If so, how did we ever run a successful job in the first place? WE need to validate what is going on here.

**Comment by richardbremner** [comment]
This feels like it could be about which pk was used to deploy the contracts, and perhaps the job creator wasn't the "owner" and was unable to calls it's contract?

**Comment by AquiGorka** [comment]
Let's keep this on the radar, when we have tests in place we can dig further down this rabbit hole
