### ISSUE TITLE
[core] Need to run solver, job-creator with --disable-pow

### ISSUE THREAD

**Issue by walkah** [Lilypad-Tech/lilypad#205]
Following the merge of https://github.com/Lilypad-Tech/lilypad/pull/203 , we need to update the deployments to run non-RP services with --disable-pow so they're not doing PoW jobs.

**Comment by hunjixin** [comment]
the pow code only in rp,  the 'solver job-create' has nothing to do with 'pow' at all." i think this issue can close directly

**Comment by AquiGorka** [comment]
The 2 places I can think of:
- [x] GitHub workflow for the CPU RP
- [x] stack
