### ISSUE TITLE
[community] Directory '/app/lilypad' does not exist

### ISSUE THREAD

**Issue by developersteve** [Lilypad-Tech/lilypad#236]
We are seeing users experience an issue with the env file `resource-provider-gpu.env` not being created during the resource provider deployment process because the directory `/app/lilypad` does not existing. 

This is on all supported operating systems. 

[Link to thread](https://discord.com/channels/1212897693450641498/1257956504032641036)

**Comment by likhita-8091** [comment]
you can mkdir

**Comment by developersteve** [comment]
> you can mkdir

Yes this is a good short term fix, although I would be was also wanting to capture this for a potential longer term fix as a few users on different operating systems were reporting this as an issue.

**Comment by likhita-8091** [comment]
At present, official documents may not be complete and there may be omissions

**Comment by bgins** [comment]
We have reports this has been resolved. Please comment if that's not the case and we can re-open this issue.

**Comment by logan-wrld** [comment]
This means lilypad could not find the .env file. Note from Wings- Thank you Brian. ![image](https://github.com/user-attachments/assets/bce1c51c-bfed-49aa-adfa-5f454b9511f0)
