### ISSUE TITLE
[core] Validate a RP being sent a deal has enough funds to pay for the txs for the process

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#250]
During matchmaking, let's add a check to validate the RP has `eth` to pay for the fees associated with resolving the job - if we don't do this, we may end up sending jobs to nodes that will never return the results.

**Comment by alvin-reyes** [comment]
We can use the cron-server check faucet job as a reference https://github.com/Lilypad-Tech/cron-server/blob/main/internal/jobs/check_faucet.go

**Comment by walkah** [comment]
Closed via https://github.com/Lilypad-Tech/lilypad/pull/298
