### ISSUE TITLE
[core] Remove GCP deprecation notice 

### ISSUE THREAD

**Issue by walkah** [Lilypad-Tech/lilypad#272]
As part of https://github.com/Lilypad-Tech/lilypad/issues/131 , we added a deprecation notice for the old GCP infrastructure. We should be able to get rid of this now. 

Code was added here: https://github.com/Lilypad-Tech/lilypad/pull/138

**Comment by narbs91** [comment]
PR: https://github.com/Lilypad-Tech/lilypad/pull/282
