### ISSUE TITLE
Remove Doppler dependency from `stack`

### ISSUE THREAD

**Issue by bgins** [Lilypad-Tech/lilypad#278]
Our current [`stack`](https://github.com/Lilypad-Tech/lilypad/blob/main/stack) implementation relies on Doppler secrets to configure some commands. Let's remove this dependency to make local development easier for open source contributors and community members.

We will need another way to configure local environments, possibly using an environment file. These environments can be public as we will not use them anywhere outside of a local development context.

**Comment by alvin-reyes** [comment]
tagging @dev-ronelcanaria. He is working on moving from doppler to 1pass (still pending access).

**Comment by walkah** [comment]
@alvin-reyes I don't think we want to require 1password for `stack` / local development - it's a barrier for open source contributors - right, @bgins ?

**Comment by bgins** [comment]
> @alvin-reyes I don't think we want to require 1password for `stack` / local development - it's a barrier for open source contributors - right, @bgins ?

Yes, that's correct. When the work on this issue is complete, we won't need any secrets management for local development.

**Comment by narbs91** [comment]
As of Aug 14th this issue has a PR up for review; however, one final bug remains to be squashed where the run-onchain-cowsay job doesn't get picked up by the job-creator locally
