### ISSUE TITLE
Add unit tests to CI

### ISSUE THREAD

**Issue by bgins** [Lilypad-Tech/lilypad#279]
We have a set of unit tests that should be run prior to merging a PR to `main`. Let's add a GitHub action to run the tests and make it a required check before merging.

At lease one unit test is failing, so they may need some attention before we start requiring them.

**Comment by robertjitaru** [comment]
Can you assign this task for the community? I can help with the implementation

**Comment by bgins** [comment]
> Can you assign this task for the community? I can help with the implementation

Assigned to community! Thanks for taking it on, much appreciated. ❤️
