### ISSUE TITLE
Schedule jobs to run with Lilypad

### ISSUE THREAD

**Issue by richardblythman** [Lilypad-Tech/lilypad#30]
We want to be ready to load up the Lilypad network with jobs that RPs can run when the incentivized testnet is launched. A simple way of doing this is using cron or systemd timers as a JC.

To start just get the scheduling running with any job (like the cowsay example). Later, we can aim to get it working with something more useful (like a data processing flow that uses LLMs).

**Comment by Nasfame** [comment]
We recently rolled out support for smart-contracts in v2:

https://github.com/bacalhau-project/lilypad/blob/main/docs/smart-contract-jobs.md


[  Automate the contracts with chainlink](https://docs.chain.link/chainlink-automation/guides/job-scheduler)

**Comment by kquirapas** [comment]
Closing this with our `lilypad-discord-observer` implementation here: https://github.com/Lilypad-Tech/lilypad-discord-observer

### Sample Integration Test for 10 Random (Currently Cowsay) Jobs

![Screenshot 2024-09-11 at 1 17 01 PM](https://github.com/user-attachments/assets/f229a916-4ef5-4e7f-b756-949d5f17b790)
