### ISSUE TITLE
Investigate/Fix Controller hardhat unit tests

### ISSUE THREAD

**Issue by robertjitaru** [Lilypad-Tech/lilypad#335]
### Describe the bug

Please investigate why Controller unit tests are failing at this moment

### Reproduction

In order to run Controller unit tests you must navigate hardhat/test/controller.ts and replace `describe.skip("Controller", () => { ` with `describe("Controller", () => { `

You can run all the unit testing using script from the main folder:
 ./stack unit-tests

### System Info

```shell
N/A
```

### Severity

Annoyance

**Comment by sigmundxyz** [comment]
I would like to be assigned to this ticket

**Comment by bgins** [comment]
> I would like to be assigned to this ticket

Thanks for taking this one on! ❤️ 

I have assigned you the issue. @arsen3d will be around if you have questions about the task.

**Comment by bgins** [comment]
Closed by #374
