### ISSUE TITLE
Add discord bot framework, community issues and leaderboard

### ISSUE THREAD

**Issue by robertjitaru** [Lilypad-Tech/lilypad#358]
Develop a GitHub Action script that queries a Lilypad GitHub repository to filter issues with the label 'community'. The script should then format and send these filtered tasks to a designated Discord channel. This will help streamline communication and keep the community updated on relevant issues and contributions.

**Comment by robertjitaru** [comment]
This is how the message that will come automatically on Discord every Monday and Friday will look like:
<img width="858" alt="image" src="https://github.com/user-attachments/assets/edba872b-3b1b-4ec0-ac5e-f53103c73644">

**Comment by bgins** [comment]
See https://github.com/Lilypad-Tech/community-bots/pull/1 for implementation.
