### ISSUE TITLE
Generate Contributors Leaderboard

### ISSUE THREAD

**Issue by robertjitaru** [Lilypad-Tech/lilypad#359]
Develop a GitHub Action script that queries a Lilypad GitHub repository to filter issues with the label 'community' and status closed. Generate a leaderboard with all contributors and and send the results to Discord

**Comment by robertjitaru** [comment]
This is the leaderboard:
<img width="767" alt="image" src="https://github.com/user-attachments/assets/43bf64dc-d7a9-4c63-a5a8-99379bb95418">

The ranking is formed and badges are assigned after each threshold according to this format:
⭐ Rising Star: For contributors with 1–2 issues solved.
🥉 Bronze Contributor: For contributors with 3–5 issues solved.
🥈 Silver Contributor: For contributors with 6–10 issues solved.
🥇 Gold Contributor: For contributors with 10+ issues solved.

**Comment by bgins** [comment]
Closed in favor of #358
