### ISSUE TITLE
Lilypad Docker RP Fails Post-Bacalhau Preflight Check - regression 2.5.0

### ISSUE THREAD

**Issue by robertjitaru** [Lilypad-Tech/lilypad#360]
Lilypad Docker RP Fails Post-Bacalhau Preflight Check - regression in 2.5.0 cause by https://github.com/Lilypad-Tech/lilypad/commit/c9a349c8d834f7f2620aecd0f91c11a1c19c3471

**Comment by robertjitaru** [comment]
Fixed by: https://github.com/Lilypad-Tech/lilypad/commit/ea0574ba17a7bbaf66a6f36ebcb1581d6706a22a

**Comment by bgins** [comment]
Closed by: https://github.com/Lilypad-Tech/lilypad/pull/357
