### ISSUE TITLE
Cron-server PoW signal monitor Bot

### ISSUE THREAD

**Issue by galaxyxtwo** [Lilypad-Tech/lilypad#394]
A Discord bot to monitor the PoW signal sent from the Lilypad cron server. The bot will monitor the Arbiscan address 0xd10d15cc705f7d2558352b1212a9b3685155d93d looking for method 0xb681f2fd. If this method is not transacted on this address within 1 hour send a warning message to the Lilypad Discord (ask the team which channel to use).

Info:
Testing
- Test the bot using a test Discord server or ask the Lilypad team for access to a channel in the Lilypad Discord. 

Implementation
- The Lilypad team will provide the Discord webhook and Arbiscan API URLs as Github secrets in this repo. Let the team know which ENV variables you intend to use so they can be added.

Address on Arbitrum Sepolia
- https://sepolia.arbiscan.io/address/0xd10d15cc705f7d2558352b1212a9b3685155d93d

**Comment by robertjitaru** [comment]
@galaxyxtwo, this one ca be assigned to me

**Comment by robertjitaru** [comment]
Implemented by: https://github.com/Lilypad-Tech/community-bots/pull/8
