### ISSUE TITLE
Extend community bots to monitor multiple repositories

### ISSUE THREAD

**Issue by bgins** [Lilypad-Tech/lilypad#395]
In #358 we added a bot framework to report community issues and a leaderboard for open source contributions. Let's extend this framework to observe and report on multiple repositories.

We can start by monitoring:

- https://github.com/Lilypad-Tech/lilypad (already monitoring)
- https://github.com/Lilypad-Tech/community-bots (new)

The extension should make it easy for the Lilypad team to add arbitrary repositories where our open source program is active.

**Comment by robertjitaru** [comment]
@bgins, you can assign this to me. I can extend the current function to check a list of repos

**Comment by galaxyxtwo** [comment]
PR has been reviewed and merged https://github.com/Lilypad-Tech/community-bots/pull/9. Thanks @Rodebrechtd!
