### ISSUE TITLE
Add solver HTTP rate limiting

### ISSUE THREAD

**Issue by bgins** [Lilypad-Tech/lilypad#417]
We have noticed the solver may receive unbounded requests from job creators or resource providers. Let's add a rate limiter to limit traffic to an acceptable threshold.

We can start with a simple policy to set a limit by IP address and route. For example we could use `go-chi/httprate`: https://github.com/go-chi/httprate#rate-limit-by-ip-and-url-path-aka-endpoint.

**Comment by walkerlj0** [comment]
@kelindi  to review @bgins PR for adding rate limiting
