### ISSUE TITLE
Bacalhau not identifying Docker container for targeted job

### ISSUE THREAD

**Issue by PBillingsby** [Lilypad-Tech/lilypad#440]
### Describe the bug

Bacalhau is not identifying the Docker container for a targeted job on Lilypad. When attempting to run the job:

**CLI response**: Job completes but returns empty results

**RP Logs of targeted node**: An error message appears stating: "Node does not support docker, only wasm."

### Reproduction

1. Send a targeted job to a Docker RP node you have log access to: 
`lilypad run --target <DOCKER RP ADDRESS> sdxl-pipeline:v0.9-base-lilypad3 --web3-private-key $WEB3_PRIVATE_KEY -i Prompt="an astronaut floating against a white background"`
2. Observe job accepted but no results
3. Check the latest RP logs using `sudo docker logs lilypad-resource-provider`
4. Observe error `not enough nodes to run job` from logs

Here are some lines of code that might help debug where these errors are coming from and why they're occurring:
**Lilypad code**: 
[`pkg/resourceprovider/controller.go`](https://github.com/Lilypad-Tech/lilypad/blob/main/pkg/resourceprovider/controller.go#L480)

**Bacalhau code**:
Search "not enough nodes to run job." in file below.
[`pkg/orchestrator/errors.go`](https://github.com/bacalhau-project/bacalhau/blob/v1.3.2/pkg/orchestrator/errors.go)

### Logs

```shell
2024-11-14T20:01:20Z ERR pkg/resourceprovider/controller.go:481 > 🔵 RP error running job="error running command Qmd4AgAQ1JHRaGSSwDwBopUbrFQ5cxXYTgWRW1JyRKKeDu -> Error submitting job: not enough nodes to run job. requested: 1, available: 1, suitable: 0. • Node n-c99b607b: does not support docker, only wasm Job Results By Node:, 4637605e-f1ae-4910-9a2a-d928c524154a"
```

### System Info

```shell
Lilypad version (CLI and RP): 2.9.0
Bacalhau version: 1.3.2
OS running CLI job: Mac M1
```

### Severity

Blocking an upgrade

**Comment by rhochmayr** [comment]
Has docker been tested or confirmed to work on the RP outside of LP jobs? E.g. can you execute docker commands within the instance where Bacalhau is active?

**Comment by walkah** [comment]
@PBillingsby thanks for the report! Is this using the new docker-compose file?

**Comment by PBillingsby** [comment]
> @PBillingsby thanks for the report! Is this using the new docker-compose file?

Yes, tested using docker-compose!
