### ISSUE TITLE
Specs: how to correctly match Jobs to GPU sizes

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#58]
Current workaround: RAM hack (use RAM to determine job matching).

The goal of this task is to define how to correctly do the matching so that when works gets started on it whoever takes on the task has clarity on how to do it.

**Comment by Zorlin** [comment]
We need a PR from Bacalhau to enable VRAM sizes to match to jobs

**Comment by Zorlin** [comment]
For now the hack we're using is sustainable enough to ship with for the next 6-9 months

**Comment by Zorlin** [comment]
This will ship *after* incentivenet; the hack will be documented as part of this before we consider this done.
