### ISSUE TITLE
Error: No solver service specified - please use SERVICE_SOLVER or --service-solver

### ISSUE THREAD

**Issue by hakymulla** [Lilypad-Tech/lilypad#7]
Using the mac m1 binary provided by Hiro Hamada here https://bacalhauproject.slack.com/archives/C055K39J9QW/p1696537153091329?thread_ts=1696438693.499459&cid=C055K39J9QW.

Running: lilypad run github.com/username/repo:tag -i Message=moo
Error: No solver service specified - please use SERVICE_SOLVER or --service-solver
export SERVICE_SOLVER="0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC" solves this.

Running: lilypad run github.com/username/repo:tag -i Message=moo. again 
Error: No mediators services specified - please use SERVICE_MEDIATORS or --service-mediators
export SERVICE_MEDIATORS="0x90F79bf6EB2c4f870365E785982E1f101E93b906"

Works fine .

**Comment by lukemarsden** [comment]
This is really strange. Hopefully will get fixed when we start shipping proper Darwin arm64 builds.

**Comment by bgins** [comment]
We have included default solver and mediator services in our embedded configs: https://github.com/Lilypad-Tech/lilypad/tree/main/pkg/options/configs

It's unlikely this error should come up with the default values, but let's re-open if it does.
