### ISSUE TITLE
[infra] Decentralize solvers

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#71]

**Comment by AquiGorka** [comment]
In the next few days I'm going to start work on a test suite for the network (network tests?), I'll report back if I find evidence that we can simulate scenarios with the implementation and maybe we can use it for this task.

**Comment by DeveloperAlly** [comment]
Discussing with @clint and CEL today -> solver shouldn't be decentralised for awhile. Going to close this one
