### ISSUE TITLE
[core] How to trigger/work with the mediator?

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#78]
What's the expectation here?
- If an audit fails, do we get an output?
- Where does the alarm sound?
- Does it run a % of the time with all jobs?

**Comment by AquiGorka** [comment]
A reference on this: https://github.com/Lilypad-Tech/lilypad/blob/d63d8b5a668f80087ed28040947920041d3fdf70/pkg/options/job-creator.go#L22-L26

**Comment by walkah** [comment]
This is likely to change.
