### ISSUE TITLE
[core] Looks like bacalhau is connecting to peers even in private mode, let's fix this

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#80]
https://github.com/bacalhau-project/bacalhau/issues/3095

**Comment by Zorlin** [comment]
We can work around this by adding a section in our Node Setup guide that explicitly asks the user to configure Bacalhau.

This might be worth doing anyways as some users are reporting to run an RP they need to initialise the IPFS repo that Bacalhau uses (using Kubo) manually, which will add some manual Bacalhau steps. I'm happy to write the PR

~w
