### ISSUE TITLE
Improve cli installation experience

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#82]
Regards to the following comment: https://discord.com/channels/1212897693450641498/1222749187804758057/1238288718792622120

**Comment by logan-wrld** [comment]
Like the Homebrew install found here, https://brew.sh/ I am to write an install script that installs Lilypad on multiple systems and then put that script on Github and then have a curl request and command that pulls the script and runs it. Just like the Homebrew example. 

Example Homerew Script: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by developersteve** [comment]
+1 on a brew install!

**Comment by noryev** [comment]
Automatic update function: https://github.com/Lilypad-Tech/lilypad-docs/pull/48 - Being tested! 

Docker Resource Provider Setup with Docs: https://github.com/Lilypad-Tech/lilypad/commit/d83023239a564c0bdb0abb78242e4212d8c8ef6c
