### ISSUE TITLE
[core] Define release strategy

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#91]
We want to define the release strategy. Currently, we have CI+CD pipelines on changes to main for `devnet`, with the intention of testing things there and then releasing to `testnet` (manually). We may want to take a look at [`Release please`](https://github.com/googleapis/release-please) for the strategy.

We also want to add
- semver to releases (that are in sync or work ok with go versioning)

cc @AquiGorka @bgins

**Comment by bgins** [comment]
See https://www.notion.so/lilypadnetwork/Release-Pipeline-70ecc09bed8b406ba33e7e1e4c4e93b3 and https://github.com/Lilypad-Tech/lilypad/pull/206 for documentation and implementation of our release strategy.
